### ISSUE TITLE
Couldn't get the DLL for snes9x to load on Windows 10

### ISSUE THREAD

**Issue by mustardseed312** [Scorr/RetroUnity#5]
I tried both the 32-bit and 64-bit dll for the snes9x core, but neither one would load. Are there any other settings I need to set to get Unity to load the dll? Is there a certain version dll I need to use? Thanks!

**Comment by Scorr** [comment]
I'm also using Windows 10. Just tested and confirmed the latest version of the 64-bit dll works for me, the 32-bit version doesn't. I got it from here:
http://buildbot.libretro.com/nightly/windows/x86_64/latest/

Both snes9x_libretro.dll and snes9_next_libretro.dll seem to load for me. Note that these are libretro cores instead of the standard snes9x.dll.

Try the one from the link above and see if it works.
